# Generated by Django 3.1.7 on 2021-12-12 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, default='Put your URL here', max_length=500)),
                ('data', models.TextField(blank=True, default='[]')),
            ],
        ),
    ]
