# Generated by Django 3.1.7 on 2021-12-13 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Find',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(blank=True, default='Put your key word here', max_length=500)),
                ('keydata', models.TextField(blank=True, default='[]')),
            ],
        ),
    ]
