# Generated by Django 3.1.7 on 2021-12-17 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('find', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Find',
        ),
    ]
